repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
  - id: check-symlinks
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: local
  hooks:
  - id: forbidden-file-extensions
    name: forbidden-file-extensions
    entry: disallow these file extensions
    language: fail
    # Disallow other asciidoc extensions except .adoc
    files: .*\.(asciidoc|asc)$
